### ISSUE TITLE
Differences with racer.el ?

### ISSUE THREAD

**Issue by bandali** [emacs-pe/company-racer#1]
Hi @marsam,

I was planning a pull request for racer (https://github.com/phildawes/racer/blob/master/editors/racer.el) to prepare it for being included MELPA, but I just found this repo, which is already included.

Can you please explain the differences between `company-racer.el` vs `racer.el`?

**Comment by marsam** [comment]
Hi:

Sorry for the late response, I was really busy.

[racer](https://github.com/phildawes/racer) currently offers “completion” and “find to definition”. Both
packages offer support completion using [company-mode](https://github.com/company-mode/company-mode), so I think
you can use both packages indistinctly to make completions.

I guess your question is **“how different both packages make completion
using [company-mode](https://github.com/company-mode/company-mode)”**.

> Note: this is my first `company-` package, so maybe there are in
> consistences how I think [company-mode](https://github.com/company-mode/company-mode) works and how actually
> works.

In a few words, [company-mode](https://github.com/company-mode/company-mode) needs:
1. **A prefix function**: to extract the `prefix` to make the completions.
2. **A candidates function**: to given the `prefix` return candidates to make the completion.

## How `racer.el` works to make completions
1. **the prefix function**: to extract the `prefix` [racer.el writes](https://github.com/phildawes/racer/blob/7fa9499/editors/racer.el#L75) the contents of the
   current buffer in a temporary file and the racer `prefix` sub
   command using [process-lines](http://doc.endlessparentheses.com/Fun/process-lines.html) to obtain the prefix in the current
   point, and finally deletes the temporary file.
2. **The candidates function**: [does the same](https://github.com/phildawes/racer/blob/7fa9499/editors/racer.el#L51) but using the racer `complete`
   sub command.

## How `company-racer.el` make completions
1. **the prefix symbol**: extracts the symbol at point using using a
   modified syntax table of the [rust-mode](https://github.com/rust-lang/rust-mode). It needs to be an
   modified syntax table because currently the colon character (`:`)
   is not considered symbol. And we use the colon character to make
   completion of rust namespaces.
2. **the candidates function**: given the prefix selects the right
   method to make completion, because racer offers two sub commands to
   extract the completions:
   
   ```
   $ racer complete linenum charnum fname
   $ racer complete fullyqualifiedname   (e.g. std::io::)
   ```
   
   In the first option, this package writes to the same temporary
   file every time [1]. And underneath uses [deferred.el](https://github.com/kiwanami/emacs-deferred) to make it asynchronous

Tell me if I could answer your question.

[1] I’m not sure if this is the best way to do this, though.

**Comment by bandali** [comment]
Hi @marsam, No problems.

That's a very detailed and awesome explanation, and it does [more than] answer my question. Thank you!

I was planning to ask this question over email but I couldn't find an actual email of yours, so I opened an issue.

BTW, thanks for this great package.

**Comment by marsam** [comment]
Thanks. Don't hesitate to open an issue if you have further questions.
